### ISSUE TITLE
Support launching epmd -daemon

### ISSUE THREAD

**Issue by bendiken** [nerves-project/erlinit#8]
In attempting to dynamically configure Erlang distribution at runtime using `Node.start` and `Node.set_cookie`, in lieu of statically configuring the node name and cookie in `rel/vm.args` when building the firmware, I ran into the blocker that Erlang doesn't automatically start the `epmd` daemon when no `-name` or `-sname` is argument is given when starting the VM:

    $ killall epmd
    $ iex
    Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

    Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)> Node.start(:"dynamic@arto.local")

    03:18:41.418 [info]  Protocol 'inet_tcp': register/listen error: econnrefused

    {:error,
     {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}},
      {:child, :undefined, :net_sup_dynamic,
       {:erl_distribution, :start_link,
        [[:"dynamic@arto.local", :longnames, 15000], false]}, :permanent, 1000,
       :supervisor, [:erl_distribution]}}}

In order to support at-runtime node configuration, then, it is necessary to manually start the `epmd` daemon with the same command-line as Erlang uses, namely `epmd -daemon`.

Ideally, this could be done through an additional option in `erlinit.config`, given how core this functionality is to enabling distributed Nerves in production uses.

I'd be happy to formulate an initial patch if this is a feature you'd consider merging, @fhunleth.

**Comment by fhunleth** [comment]
I'm pretty sure that you can start `epmd` from inside Elixir. I'll have to look at my notes from when I did this before.

**Comment by fhunleth** [comment]
This is some really old Erlang code of mine, but apparently I just started it manually: https://github.com/fhunleth/relsync/blob/master/src/relsync.erl#L42-L48.

I'm not sure whether this will work on a Nerves node, though. If not, it should be possible to make it work.

**Comment by bendiken** [comment]
Thanks. I consider this part of OTP bootstrap that my app shouldn't need to care about, so I went ahead and solved this by configuring `--alternate-exec /bin/erlwrap.sh` in `/etc/erlinit.config`, and creating `/bin/erlwrap.sh` in my rootfs overlay, with contents:

    #!/bin/sh
    echo "Starting EPMD..."
    /usr/lib/erlang/bin/epmd -daemon
    echo "Starting OTP..."
    exec $*

**Comment by fhunleth** [comment]
That may be true, but there should be another way of accomplishing this. In Nerves, the OTP release is everything. This isn't a Unix system where it's just one of many components. Since your OTP Application is just one of many, it need not have this logic. Place it in another OTP Application or if there's a way with exrm to include this in the OTP initialization script, but it there. @mobileoverlord has been wanting to start a common project for shared runtime OTP applications for Nerves so we could even put it there, but it would have to be optional. Using `--alternate-exec` in this way should only be used as a temporary workaround.

**Comment by bendiken** [comment]
A common OTP app makes sense. After all, `epmd` _should_ be supervised, as it's been known to potentially crash in rare circumstances (historically, anyhow).

**Comment by fhunleth** [comment]
Thanks for understanding. I view initialization shell scripting as a very slippery slope especially since we don't have a convention for handling initialization tasks yet. I am hopeful that your work in this area will help all of us in figure out what that convention should be. Also, if I'm able to remove busybox from Nerves some day, I will view that as a huge success of the breadth of the embedded Elixir ecosystem. (Don't worry - removing busybox is so impractical right now that it's not in jeopardy.)
