### ISSUE TITLE
Support for /etc/rc.local script

### ISSUE THREAD

**Issue by bendiken** [nerves-project/erlinit#9]
A functionality that I found sorely missing (AFAICT) in `erlinit` is the ability to launch an arbitrary shell script where additional initialization actions can be readily and trivially be performed just prior to starting up the Erlang VM.

A minimal pass at this wouldn't even need any configuration in `erlinit.config`; as per long-standing Linux conventions, it'd suffice just fine to check whether an `/etc/rc.local` script exists (it would originate from a user-configured rootfs overlay), and if it does exist, to execute it using `/bin/sh`.

What do you think, @fhunleth?

**Comment by fhunleth** [comment]
I'd like to avoid this if at all possible. It splits the initialization up into bash script parts and Erlang and Elixir parts which will lead to confusion as to where initialization should occur. I know that it's probably just one thing now, but I know from my own experience that the tendency will be to move more initialization to bash since it's easy and familiar rather than properly supervise it in Erlang. I realize that Erlang and Elixir have limitations on the initialization front, but I'd like to move in the direction of fixing them. How about we address the initialization issues on a case by case basis? 

If you get too frustrated with this limitation, you can actually already hook into the initialization path with a shell script with the `erlinit.config`, but hopefully we can just use that as a bandaid while we wait for a proper fix if we need something done with the Erlang VM.

**Comment by bendiken** [comment]
> If you get too frustrated with this limitation, you can actually already hook into the initialization path with a shell script with the erlinit.config, but hopefully we can just use that as a bandaid while we wait for a proper fix if we need something done with the Erlang VM.

Do you mean the `--pre-run-exec` option? I don't know how I missed that one, but will give it a go.

**Comment by fhunleth** [comment]
Yes, and there's also `--alternate-exec` if you need to wrap the start up of the Erlang VM.

**Comment by bendiken** [comment]
Thanks; those sound like plenty of options, I'll check them out.

**Comment by bendiken** [comment]
@fhunleth: The `--pre-run-exec` option appears to have no effect in current released versions of Nerves. I see that it was added recently (in 116a8f324e60922516735bb0925945685cc205ad). Is there an ETA for the next release, or is there another way I can pull in this feature into a downstream Nerves project?
